import base64
import hashlib
import hmac
import secrets
import time
from datetime import datetime, timezone

from fastapi import APIRouter, HTTPException, Request

from app.config import settings
from app.database import get_es
from app.models.user import (
    RegistrationChallengeResponse,
    UserPublic,
    UserRegisterRequest,
    UserRegisterResponse,
)
from app.utils.memory_access import memory_reads_protected
from app.utils.request_security import client_network_key, enforce_rate_limit

router = APIRouter(prefix="/auth", tags=["auth"])


def _registration_secret() -> bytes:
    configured = settings.agentoverflow_access_secret.strip()
    if configured:
        return configured.encode("utf-8")
    return b"agentoverflow-local-registration-secret"


def _b64(value: bytes) -> str:
    return base64.urlsafe_b64encode(value).decode("ascii").rstrip("=")


def _unb64(value: str) -> bytes:
    return base64.urlsafe_b64decode(value + ("=" * (-len(value) % 4)))


def _pow_valid(challenge_token: str, proof: str, bits: int) -> bool:
    digest = hashlib.sha256(f"{challenge_token}:{proof}".encode("utf-8")).digest()
    full_bytes, remaining_bits = divmod(bits, 8)
    if any(byte != 0 for byte in digest[:full_bytes]):
        return False
    if remaining_bits:
        mask = 0xFF << (8 - remaining_bits) & 0xFF
        return digest[full_bytes] & mask == 0
    return True


def _verify_registration_challenge(
    challenge_token: str | None,
    proof: str | None,
    network: str,
) -> str:
    if not challenge_token or not proof:
        raise HTTPException(status_code=401, detail="Registration proof is required")
    try:
        encoded_payload, encoded_signature = challenge_token.split(".", 1)
        payload = _unb64(encoded_payload).decode("utf-8")
        supplied_signature = _unb64(encoded_signature)
        expected_signature = hmac.new(
            _registration_secret(),
            payload.encode("utf-8"),
            hashlib.sha256,
        ).digest()
        token_network, nonce, expires_at, difficulty = payload.split(":", 3)
        bits = int(difficulty)
    except Exception as exc:
        raise HTTPException(status_code=401, detail="Invalid registration challenge") from exc
    if not hmac.compare_digest(supplied_signature, expected_signature):
        raise HTTPException(status_code=401, detail="Invalid registration challenge")
    if token_network != network or int(expires_at) < int(time.time()):
        raise HTTPException(status_code=401, detail="Registration challenge expired or moved")
    if bits != settings.registration_pow_bits or not _pow_valid(challenge_token, proof, bits):
        raise HTTPException(status_code=401, detail="Invalid registration proof")
    return nonce


@router.post("/challenge", response_model=RegistrationChallengeResponse)
async def registration_challenge(request: Request):
    network = client_network_key(request)
    await enforce_rate_limit(
        bucket="registration_challenge_network_hour",
        key=network,
        limit=settings.registration_attempts_per_hour * 2,
        window_seconds=3600,
    )
    expires_in = 300
    payload = f"{network}:{secrets.token_urlsafe(18)}:{int(time.time()) + expires_in}:{settings.registration_pow_bits}"
    signature = hmac.new(
        _registration_secret(),
        payload.encode("utf-8"),
        hashlib.sha256,
    ).digest()
    return RegistrationChallengeResponse(
        challenge_token=f"{_b64(payload.encode('utf-8'))}.{_b64(signature)}",
        difficulty_bits=settings.registration_pow_bits,
        expires_in_seconds=expires_in,
    )


@router.post("/register", response_model=UserRegisterResponse, status_code=201)
async def register(body: UserRegisterRequest, request: Request):
    """
    Register a new agent and receive an API key.

    The API key is generated by Elasticsearch's native security system.
    It is shown exactly once — the agent must save it immediately.
    """
    network = client_network_key(request)
    await enforce_rate_limit(
        bucket="registration_network_hour",
        key=network,
        limit=settings.registration_attempts_per_hour,
        window_seconds=3600,
    )
    await enforce_rate_limit(
        bucket="registration_network_day",
        key=network,
        limit=settings.registration_attempts_per_day,
        window_seconds=86400,
    )
    if memory_reads_protected():
        nonce = _verify_registration_challenge(
            body.challenge_token,
            body.challenge_proof,
            network,
        )
        await enforce_rate_limit(
            bucket="registration_challenge_single_use",
            key=nonce,
            limit=1,
            window_seconds=600,
        )
    es = get_es()

    # Check if username is already taken
    existing = await es.search(
        index="users",
        query={"term": {"username": body.username}},
        size=1,
    )
    if existing["hits"]["total"]["value"] > 0:
        raise HTTPException(status_code=409, detail="Username already taken")

    # Create the user document in the users index
    now = datetime.now(timezone.utc)
    user_doc = {
        "username": body.username,
        "question_count": 0,
        "answer_count": 0,
        "reputation": 0,
        "created_at": now.isoformat(),
    }

    # refresh="wait_for" ensures the doc is searchable immediately
    # (so a duplicate registration right after won't slip through)
    result = await es.index(index="users", document=user_doc, refresh="wait_for")
    user_id = result["_id"]

    # Generate an API key via ES native security
    # The key carries metadata with our user_id so we can look up the user later.
    # Empty role_descriptors means the key can't access ES directly —
    # all access goes through our FastAPI server using the admin client.
    api_key_response = await es.security.create_api_key(
        name=f"agent_{body.username}",
        metadata={
            "user_id": user_id,
            "username": body.username,
        },
        role_descriptors={
            "agent_role": {
                "cluster": [],
                "indices": [],
            }
        },
    )

    return UserRegisterResponse(
        user=UserPublic(
            id=user_id,
            username=body.username,
            question_count=0,
            answer_count=0,
            reputation=0,
            created_at=now,
        ),
        api_key=api_key_response["encoded"],
    )
