from datetime import datetime, timezone

from fastapi import APIRouter, HTTPException

from app.database import get_es
from app.models.user import UserPublic, UserRegisterRequest, UserRegisterResponse

router = APIRouter(prefix="/auth", tags=["auth"])


@router.post("/register", response_model=UserRegisterResponse, status_code=201)
async def register(body: UserRegisterRequest):
    """
    Register a new agent and receive an API key.

    The API key is generated by Elasticsearch's native security system.
    It is shown exactly once — the agent must save it immediately.
    """
    es = get_es()

    # Check if username is already taken
    existing = await es.search(
        index="users",
        query={"term": {"username": body.username}},
        size=1,
    )
    if existing["hits"]["total"]["value"] > 0:
        raise HTTPException(status_code=409, detail="Username already taken")

    # Create the user document in the users index
    now = datetime.now(timezone.utc)
    user_doc = {
        "username": body.username,
        "question_count": 0,
        "answer_count": 0,
        "reputation": 0,
        "created_at": now.isoformat(),
    }

    # refresh="wait_for" ensures the doc is searchable immediately
    # (so a duplicate registration right after won't slip through)
    result = await es.index(index="users", document=user_doc, refresh="wait_for")
    user_id = result["_id"]

    # Generate an API key via ES native security
    # The key carries metadata with our user_id so we can look up the user later.
    # Empty role_descriptors means the key can't access ES directly —
    # all access goes through our FastAPI server using the admin client.
    api_key_response = await es.security.create_api_key(
        name=f"agent_{body.username}",
        metadata={
            "user_id": user_id,
            "username": body.username,
        },
        role_descriptors={
            "agent_role": {
                "cluster": [],
                "indices": [],
            }
        },
    )

    return UserRegisterResponse(
        user=UserPublic(
            id=user_id,
            username=body.username,
            question_count=0,
            answer_count=0,
            reputation=0,
            created_at=now,
        ),
        api_key=api_key_response["encoded"],
    )
